[redhat] Add i386 to ExclusiveArch to fix noarch package build
Message-id: <20180504194013.13197-3-herton@redhat.com>
Patchwork-id: 7882
O-Subject: [kernel team] [RHEL8 PATCH 2/2] redhat: Add i386 to ExclusiveArch to fix noarch package build
Bugzilla: 1575152
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=15984835

I'm not sure if this is "bad luck" when getting an x86 host on brew for
building noarch packages, or some behaviour change after RHEL 8 buildroot
being updated/synced with Fedora 28 packages for RHEL 8 Beta. I got the
following error today when doing a brew build:

Executing command: ['bash', '--login', '-c', u'/usr/bin/rpmbuild -bb --target noarch --nodeps /builddir/build/SPECS/kernel.spec'] with env {'LANG': 'en_US.UTF-8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'HOME': '/builddir', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PS1': '<mock-chroot> \\s-\\v\\$ '} and shell False
warning: Macro expanded in comment on line 31: %{?dist} tag
error: Architecture is not included: i386
Building target platforms: noarch
Building for target noarch
Child return code was: 1
...
Error: Command failed. See logs for output.

Thus add back i386 to ExclusiveArch/nobuildarches, this should fix the build
issue. No packages are built for i386, just the 32 bits i686 headers as
before.

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>