Revert "redhat: fix elf got hardening for vm tools"
This reverts commit eb5aebd77015bc57616c5d05a7b6206c8ff871cb.

A recent rework of the tools/vm area relies on a proper CFLAGS
definition to include the proper header files.  The kernel.spec file
purposely overwrites the CFLAGS to get the right switches to pass
rpminspect.  As a consequence tools/vm fails to compile.

For now just revert the change and await a proper fix.

To duplicate:

cd tools/vm
make CFLAGS= slabinfo page_owner_sort

make -C ../lib/api
make[1]: Entering directory
'/home/dzickus/devel/git/kernel-ark/tools/lib/api'
/usr/bin/make -C /home/dzickus/devel/git/kernel-ark/tools/build CFLAGS= LDFLAGS= fixdep
  CC      fd/array.o
  LD      fd/libapi-in.o
  CC      fs/fs.o
fs/fs.c:17:10: fatal error: debug-internal.h: No such file or directory
   17 | #include "debug-internal.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [/home/dzickus/devel/git/kernel-ark/tools/build/Makefile.build:97: fs/fs.o] Error 1
make[2]: *** [/home/dzickus/devel/git/kernel-ark/tools/build/Makefile.build:139: fs] Error 2
make[1]: *** [Makefile:79: libapi-in.o] Error 2
make[1]: Leaving directory
'/home/dzickus/devel/git/kernel-ark/tools/lib/api'
make: *** [Makefile:19: ../lib/api/libapi.a] Error 2

Signed-off-by: Don Zickus <dzickus@redhat.com>