[rpmspec] add spdxcheck.py to python2to3 mangle stanza
Message-id: <20180620143438.22730-2-jracek@redhat.com>
Patchwork-id: 8273
O-Subject: [kernel team] [ARK PATCH 1/2] rpmspec: add spdxcheck.py to python2to3 mangle stanza
Bugzilla: 1593307
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=16783509
Tested: https://beaker.engineering.redhat.com/jobs/2555956
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1593307

This is an emergency build fix. This passes scripts/spdxcheck.py
to stanza instroduced in following commit:

commit c55471f297eb1e98d81ca2b39b1a89452a62cc0e
Author: Herton R. Krzesinski <herton@redhat.com>
Date:   Tue May 8 12:31:03 2018 -0400

    [rpmspec] kernel spec: fix recent build errors from brp-mangle-shebangs

    Message-id: <20180508123103.32419-1-herton@redhat.com>
    Patchwork-id: 7886
    O-Subject: [kernel team] [RHEL8 PATCH] [redhat] kernel spec: fix recent build errors from brp-mangle-shebangs
    Bugzilla: 1575966
    RH-Acked-by: Don Zickus <dzickus@redhat.com>
    RH-Acked-by: Jeff Moyer <jmoyer@redhat.com>

    Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1575966
    Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=16098628

    Recently RHEL 8 build started to complain about shebangs from some python scripts:

    + /usr/lib/rpm/redhat/brp-mangle-shebangs '' ''
    *** ERROR: ambiguous python shebang in /usr/bin/kvm_stat: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
    ...
    *** ERROR: ambiguous python shebang in /usr/src/kernels/4.16.0-11.el8+6.test.ppc64le+debug/scripts/tracing/draw_functrace.py: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
    *** ERROR: ambiguous python shebang in /usr/src/kernels/4.16.0-11.el8+6.test.ppc64le+debug/scripts/show_delta: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
    ...
    *** ERROR: ambiguous python shebang in /usr/src/kernels/4.16.0-11.el8+6.test.ppc64le+debug/scripts/diffconfig: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
    ...
    *** ERROR: ambiguous python shebang in /usr/src/kernels/4.16.0-11.el8+6.test.ppc64le+debug/scripts/bloat-o-meter: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
    ...
    *** ERROR: ambiguous python shebang in /usr/libexec/perf-core/tests/attr.py: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
    *** ERROR: ambiguous python shebang in /usr/libexec/perf-core/scripts/python/stat-cpi.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
    ...
    *** ERROR: ambiguous python shebang in /usr/libexec/perf-core/scripts/python/sched-migration.py: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
    ...
    error: Bad exit status from /var/tmp/rpm-tmp.PdJtfq (%install)
    RPM build errors:
        Macro expanded in comment on line 31: %{?dist} tag
        Bad exit status from /var/tmp/rpm-tmp.PdJtfq (%install)
    Child return code was: 1

    And because of it, the kernel build fails. We are now obliged to not ship any
    script with python shebang not specifying the major version.

    For now, just patch those scripts in %prep to get the build fixed, using a sed
    expression, this is a derivative from what Python RPM Porting guide recomends.

    What seems compatible or already ported to python3, we just replace the shebang
    with the python3 one. For python2 scripts, use python2, however, this must be
    fixed for RHEL8 later, because it's expected we will not have python 2 available
    anymore. A special mention to python-perf: it's not compatible with python3, but
    that will change when we rebase to 4.17, thus after the rebase we should fix
    python perf to ship/build with python3.

    Signed-off-by: Herton R. Krzesinski <herton@redhat.com>

Signed-off-by: Jakub Racek <jracek@redhat.com>