[vfio] vfio_pci: Add local source directory as include
Message-id: <20190105171910.25656-1-labbott@redhat.com>
Patchwork-id: 236830
O-Subject: [ARK PATCH] [vfio] vfio_pci: Add local source directory as include
Bugzilla:

Upstream: posted, see lkml.kernel.org/r/<20190104195714.30045-1-labbott@redhat.com>
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1663553

Commit 7f92891778df ("vfio_pci: Add NVIDIA GV100GL [Tesla V100 SXM2]
subdriver") introduced a trace.h file in the local directory but
missed adding the local include path, resulting in compilation
failures with tracepoints:

In file included from drivers/vfio/pci/trace.h:102,
                 from drivers/vfio/pci/vfio_pci_nvlink2.c:29:
./include/trace/define_trace.h:89:42: fatal error: ./trace.h: No such file or directory
 #include TRACE_INCLUDE(TRACE_INCLUDE_FILE)

Fix this by adjusting the include path.

Fixes: 7f92891778df ("vfio_pci: Add NVIDIA GV100GL [Tesla V100 SXM2] subdriver")
Signed-off-by: Laura Abbott <labbott@redhat.com>
---
This is a build fix needed for v4.21-rc1. My intention is to just
include this for the -rc1 release and then have this be fixed in the
regular upstream source.
---
 drivers/vfio/pci/Makefile | 1 +
 1 file changed, 1 insertion(+)

Signed-off-by: Laura Abbott <labbott@redhat.com>