[tools] objtool, perf: Fix GCC 8 -Wrestrict error
Patchwork-id: 7883
O-Subject: [kernel team] [RHEL8 PATCH 1/2] objtool, perf: Fix GCC 8 -Wrestrict error
Bugzilla: 1575152
RH-Acked-by: Rafael Aquini <aquini@redhat.com>
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>

Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=15984835

This is an "emergency" build fix and no bugzilla is being opened, as we
are yet going to rebase to 4.17 and this will then be already included.

When trying to build with GCC 8 (GCC was updated recentrly on RHEL 8 beta
buildroots), kernel build now fails with the following error:

+ make -s ARCH=x86_64 V=1 -j4 bzImage
../lib/str_error_r.c: In function 'str_error_r':
../lib/str_error_r.c:25:3: error: passing argument 1 to restrict-qualified parameter aliases with argument 5 [-Werror=restrict]
   snprintf(buf, buflen, "INTERNAL ERROR: strerror_r(%d, %p, %zd)=%d", errnum, buf, buflen, err);
   ^~~~~~~~
cc1: all warnings being treated as errors
mv: cannot stat '/builddir/build/BUILD/kernel-4.16.0-9.el8.test/linux-4.16.0-9.el8+6.test.x86_64/tools/objtool/.str_error_r.o.tmp': No such file or directory
make[3]: *** [Build:22: /builddir/build/BUILD/kernel-4.16.0-9.el8.test/linux-4.16.0-9.el8+6.test.x86_64/tools/objtool/str_error_r.o] Error 1
make[2]: *** [Makefile:46: /builddir/build/BUILD/kernel-4.16.0-9.el8.test/linux-4.16.0-9.el8+6.test.x86_64/tools/objtool/objtool-in.o] Error 2
make[1]: *** [Makefile:63: objtool] Error 2
make: *** [Makefile:1696: tools/objtool] Error 2
make: *** Waiting for unfinished jobs....

Thus cherry pick below upstream commit which fixes the issue:

commit 854e55ad289ef8888e7991f0ada85d5846f5afb9
Author: Josh Poimboeuf <jpoimboe@redhat.com>
Date:   Thu Mar 15 22:11:54 2018 -0500

    objtool, perf: Fix GCC 8 -Wrestrict error

    Starting with recent GCC 8 builds, objtool and perf fail to build with
    the following error:

      ../str_error_r.c: In function 'str_error_r':
      ../str_error_r.c:25:3: error: passing argument 1 to restrict-qualified parameter aliases with argument 5 [-Werror=restrict]
         snprintf(buf, buflen, "INTERNAL ERROR: strerror_r(%d, %p, %zd)=%d", errnum, buf, buflen, err);

    The code seems harmless, but there's probably no benefit in printing the
    'buf' pointer in this situation anyway, so just remove it to make GCC
    happy.

    Reported-by: Laura Abbott <labbott@redhat.com>
    Signed-off-by: Josh Poimboeuf <jpoimboe@redhat.com>
    Tested-by: Laura Abbott <labbott@redhat.com>
    Cc: Adrian Hunter <adrian.hunter@intel.com>
    Cc: Jiri Olsa <jolsa@kernel.org>
    Cc: Namhyung Kim <namhyung@kernel.org>
    Cc: Wang Nan <wangnan0@huawei.com>
    Link: http://lkml.kernel.org/r/20180316031154.juk2uncs7baffctp@treble
    Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>