[rpmspec] fix conflicts with COPYING file while installing newer 4.17 kernel
Message-id: <20180518145602.14211-1-herton@redhat.com>
Patchwork-id: 7910
O-Subject: [kernel team] [RHEL8 PATCH v2] [rpmspec] fix conflicts with COPYING file while installing newer 4.17 kernel
Bugzilla: 1579563
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Don Zickus <dzickus@redhat.com>

Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=16353873
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1579563

When we rebase to the 4.17 kernel, the COPYING file will change. kernel packages
can be installed in parallel, and we got away with it before because rpm will
not complain when all installed packages provide the same file with same
content. But that's not true anymore with 4.17, where contents of
COPYING changed in the upstream source, and we now get the following
error when installing 4.17 on a system with kernel 4.16:

Error: Transaction check error:
  file /usr/share/licenses/kernel-core/COPYING from install of kernel-core-4.17.0-0.rc5.1.el8+7.x86_64 conflicts with file from package kernel-core-4.16.0-8.el8+5.x86_64

Fix the kernel-core install issue, versioning the COPYING file. Use the
same solution which also Fedora used, just adding the kernel/package version.

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>